-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."endpoint" add column "response" jsonb
--  null default jsonb_build_object();
