export default (theme) => ({
  dropdown: {
    position: 'relative',
    width: 200,
    marginTop: 35,
    '& img': {
      width: 44,
      height: 44,
      borderRadius: 50,
      backgroundColor: theme.palette.common.white,
    },
    [theme.breakpoints.up('sm')]: {
      marginTop: 0,
      width: 'auto',
      minWidth: 200,
    },
    '&:hover': {
      cursor: 'pointer',
    },
  },
  list: {
    transition: 'max-height .6s ease-out',
    backgroundColor: theme.palette.background.default,
    maxHeight: 0,
    overflow: 'hidden',
    margin: 0,
    position: 'absolute',
    zIndex: 2,
    padding: 0,
    width: 310,
    top: 48,
    left: -55,
    boxShadow: theme.palette.shadows.tooltip,
    '& .titles': {
      display: 'flex',
      '& .titlesBoxRight': {
        paddingLeft: theme.spacing(2),
        display: 'flex',
        alignItems: 'center',
        width: '50%',
        height: 50,
        borderLeft: `1px solid ${theme.palette.neutral.lighter}`,
        borderBottom: `1px solid ${theme.palette.neutral.lighter}`,
      },
      '& .titlesBoxLeft': {
        paddingLeft: theme.spacing(2),
        display: 'flex',
        alignItems: 'center',
        height: 50,
        width: '50%',
        borderBottom: `1px solid ${theme.palette.neutral.lighter}`,
      },
      '& p': {
        fontWeight: 'bold',
        fontSize: 14,
        lineHeight: '21px',
        letterSpacing: '0.07875px',
      },
    },
    '& .lists': {
      display: 'flex',
      '& ul': {
        padding: 0,
        margin: 0,
      },
      '& .listsBoxRight': {
        width: '50%',
        borderLeft: `1px solid ${theme.palette.neutral.lighter}`,
      },
      '& .listsBoxLeft': {
        width: '50%',
      },
    },
    [theme.breakpoints.down('sm')]: {
      top: 85,
    },
    [theme.breakpoints.up('sm')]: {
      left: -189,
      width: 320,
    },
  },
  listActive: {
    maxHeight: 1000,
    opacity: 1,
  },
  listItem: {
    height: 50,
    display: 'flex',
    alignItems: 'center',
    cursor: 'pointer',
    listStyle: 'none',
    paddingLeft: theme.spacing(2),
    background: theme.palette.background.default,
    '& a': {
      width: '100%',
      height: '100%',
      display: 'flex',
      alignItems: 'center',
      textDecoration: 'none',
      color: theme.palette.text.primary,
    },
    '&:hover': {
      background: theme.palette.neutral.lighter,
    },
  },
  listItemActive: {
    background: theme.palette.primary.contrastText,
  },
  toggle: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: 50,
    borderRadius: theme.spacing(2),
    [theme.breakpoints.down('sm')]: {
      margin: theme.spacing(6, 0, 4),
      textAlign: 'center',
      '& > p': {
        maxWidth: 130,
      },
    },
    [theme.breakpoints.up('sm')]: {
      paddingLeft: 22,
      borderRadius: theme.spacing(2, 4, 4, 2),
      justifyContent: 'flex-start',
      marginRight: 65,
    },
  },
  networkLogo: {
    border: `2px solid ${theme.palette.primary.main}`,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: 56,
    height: 56,
    borderRadius: '100%',
    zIndex: 2,
    position: 'absolute',
    right: 70,
    top: -45,
    cursor: 'default',
    backgroundColor: theme.palette.common.white,
    [theme.breakpoints.up('sm')]: {
      right: 0,
      top: -3,
    },
  },
  expandIcon: {
    marginTop: theme.spacing(1),
    marginRight: 0,
    color: theme.palette.text.hint,
  },
  jungleImg: {
    width: '22px !important',
    height: '22px !important',
    marginRight: theme.spacing(2),
  },
  telosImg: {
    width: '21px !important',
    height: '21px !important',
    marginRight: theme.spacing(2),
  },
  waxImg: {
    width: '21px !important',
    height: '21px !important',
    marginRight: theme.spacing(2),
  },
  lacchainImg: {
    width: '24px !important',
    height: '24px !important',
    marginRight: theme.spacing(2),
  },
  xprNetworkImg: {
    width: '21px !important',
    height: '21px !important',
    marginRight: theme.spacing(2),
  },
  eosImg: {
    width: '24px !important',
    height: '24px !important',
    marginRight: theme.spacing(1),
    marginLeft: -3,
  },
  airwireImg: {
    width: '24px !important',
    height: '24px !important',
    marginRight: theme.spacing(2),
  },
  libreImg: {
    width: '24px !important',
    height: '24px !important',
    marginRight: theme.spacing(2),
  },
  ultraImg: {
    width: '24px !important',
    height: '24px !important',
    marginRight: theme.spacing(2),
  },
})
