apiVersion: v1
kind: Service
metadata:
  labels:
    app: dashboard-hapi-evm
  name: dashboard-hapi-evm
spec:
  ports:
  - name: hapi
    port: 9091
    targetPort: 9090
  selector:
    app: dashboard-hapi-evm
