-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."endpoint" add column "head_block_time" timestamp with time zone
--  null;
