-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "evm"."param" add column "is_synced" boolean
--  not null default 'false';
