apiVersion: v1
kind: Service
metadata:
  labels:
    app: monitor-webapp
  name: monitor-webapp
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  selector:
    app: monitor-webapp
