-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."stat" add column "missed_blocks_checked_at" timestamp with time zone
--  null;
