apiVersion: v1
kind: Service
metadata:
  labels:
    app: monitor-hasura
  name: monitor-hasura
spec:
  ports:
  - name: hasura
    port: 8080
    targetPort: 8080
  selector:
    app: monitor-hasura
