apiVersion: v1
kind: Service
metadata:
  labels:
    app: monitor-wallet
  name: monitor-wallet
spec:
  ports:
  - name: monitor-wallet
    port: 8888
    targetPort: 8888
  selector:
    app: monitor-wallet
