-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "evm"."incoming_transfer" add column "type" varchar
--  not null default 'incoming';
